2019-07-19 20:15:04,607 [MainThread  ] [CRITI]  Unhandled error in Deferred:
2019-07-19 20:15:04,608 [MainThread  ] [CRITI]  Unhandled error in Deferred:
2019-07-19 20:15:04,625 [MainThread  ] [CRITI]  
Traceback (most recent call last):
  File "C:\Users\toila\AppData\Local\Continuum\anaconda3\envs\crawler\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\toila\AppData\Local\Continuum\anaconda3\envs\crawler\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\toila\AppData\Local\Continuum\anaconda3\envs\crawler\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\toila\AppData\Local\Continuum\anaconda3\envs\crawler\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
TypeError: sleep() missing 1 required keyword-only argument: 'seconds'
2019-07-19 20:15:04,628 [MainThread  ] [CRITI]  
Traceback (most recent call last):
  File "C:\Users\toila\AppData\Local\Continuum\anaconda3\envs\crawler\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\toila\AppData\Local\Continuum\anaconda3\envs\crawler\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\toila\AppData\Local\Continuum\anaconda3\envs\crawler\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\toila\AppData\Local\Continuum\anaconda3\envs\crawler\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
TypeError: sleep() missing 1 required keyword-only argument: 'seconds'
2019-07-19 20:15:04,632 [MainThread  ] [CRITI]  Unhandled error in Deferred:
2019-07-19 20:15:04,632 [MainThread  ] [CRITI]  Unhandled error in Deferred:
2019-07-19 20:15:04,639 [MainThread  ] [CRITI]  
Traceback (most recent call last):
  File "C:\Users\toila\AppData\Local\Continuum\anaconda3\envs\crawler\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\toila\AppData\Local\Continuum\anaconda3\envs\crawler\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\toila\AppData\Local\Continuum\anaconda3\envs\crawler\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\toila\AppData\Local\Continuum\anaconda3\envs\crawler\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
TypeError: sleep() missing 1 required keyword-only argument: 'seconds'
2019-07-19 20:15:04,641 [MainThread  ] [CRITI]  
Traceback (most recent call last):
  File "C:\Users\toila\AppData\Local\Continuum\anaconda3\envs\crawler\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\toila\AppData\Local\Continuum\anaconda3\envs\crawler\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\toila\AppData\Local\Continuum\anaconda3\envs\crawler\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\toila\AppData\Local\Continuum\anaconda3\envs\crawler\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
TypeError: sleep() missing 1 required keyword-only argument: 'seconds'
2019-07-19 20:15:04,643 [MainThread  ] [CRITI]  Unhandled error in Deferred:
2019-07-19 20:15:04,643 [MainThread  ] [CRITI]  Unhandled error in Deferred:
2019-07-19 20:15:04,646 [MainThread  ] [CRITI]  
Traceback (most recent call last):
  File "C:\Users\toila\AppData\Local\Continuum\anaconda3\envs\crawler\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\toila\AppData\Local\Continuum\anaconda3\envs\crawler\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\toila\AppData\Local\Continuum\anaconda3\envs\crawler\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\toila\AppData\Local\Continuum\anaconda3\envs\crawler\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
TypeError: sleep() missing 1 required keyword-only argument: 'seconds'
2019-07-19 20:15:04,647 [MainThread  ] [CRITI]  
Traceback (most recent call last):
  File "C:\Users\toila\AppData\Local\Continuum\anaconda3\envs\crawler\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\toila\AppData\Local\Continuum\anaconda3\envs\crawler\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\toila\AppData\Local\Continuum\anaconda3\envs\crawler\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\toila\AppData\Local\Continuum\anaconda3\envs\crawler\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
TypeError: sleep() missing 1 required keyword-only argument: 'seconds'
2019-07-19 20:15:04,656 [MainThread  ] [CRITI]  Unhandled error in Deferred:
2019-07-19 20:15:04,657 [MainThread  ] [CRITI]  Unhandled error in Deferred:
2019-07-19 20:15:04,663 [MainThread  ] [CRITI]  
Traceback (most recent call last):
  File "C:\Users\toila\AppData\Local\Continuum\anaconda3\envs\crawler\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\toila\AppData\Local\Continuum\anaconda3\envs\crawler\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\toila\AppData\Local\Continuum\anaconda3\envs\crawler\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
TypeError: sleep() missing 1 required keyword-only argument: 'seconds'
2019-07-19 20:15:04,664 [MainThread  ] [CRITI]  
Traceback (most recent call last):
  File "C:\Users\toila\AppData\Local\Continuum\anaconda3\envs\crawler\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\toila\AppData\Local\Continuum\anaconda3\envs\crawler\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\toila\AppData\Local\Continuum\anaconda3\envs\crawler\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
TypeError: sleep() missing 1 required keyword-only argument: 'seconds'
